# Generated by Django 3.2.8 on 2023-11-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('cedulaA', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreA', models.CharField(max_length=40)),
                ('telefonoA', models.CharField(max_length=10)),
                ('contraseñaA', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPrenda',
            fields=[
                ('idCP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipoCP', models.CharField(max_length=35)),
                ('descripcionCP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedulaC', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=40)),
                ('telefonoC', models.CharField(max_length=10)),
                ('correoC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('idTS', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreTS', models.CharField(max_length=50)),
                ('descripcionTS', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('idP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('colorP', models.CharField(max_length=10)),
                ('tipotelaP', models.CharField(max_length=40)),
                ('tipoprendaP', models.CharField(max_length=40)),
                ('idCP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applavanderia.categoriaprenda')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idF', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('observacionesF', models.CharField(max_length=100)),
                ('fechayhoraF', models.DateTimeField()),
                ('estadofacturaF', models.CharField(max_length=20)),
                ('cedulaA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applavanderia.administrador')),
                ('cedulaC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applavanderia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('idDF', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applavanderia.facturas')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applavanderia.prenda')),
                ('idTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applavanderia.tiposervicio')),
            ],
        ),
    ]
